/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.scut24lab.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-30-2008
 * 
 * XDoclet definition:
 * @struts.form name="preComputeForm"
 */
public class PreComputeForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** cubeName property */
	private String cubeName;

	/** schemaName property */
	private String schemaName;
	
	private String alg;
	
	private String qryAlg;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the cubeName.
	 * @return String
	 */
	public String getCubeName() {
		return cubeName;
	}

	/** 
	 * Set the cubeName.
	 * @param cubeName The cubeName to set
	 */
	public void setCubeName(String cubeName) {
		this.cubeName = cubeName;
	}

	/** 
	 * Returns the schemaName.
	 * @return String
	 */
	public String getSchemaName() {
		return schemaName;
	}

	/** 
	 * Set the schemaName.
	 * @param schemaName The schemaName to set
	 */
	public void setSchemaName(String schemaName) {
		this.schemaName = schemaName;
	}

	public String getAlg() {
		return alg;
	}

	public void setAlg(String alg) {
		this.alg = alg;
	}

	public String getQryAlg() {
		return qryAlg;
	}

	public void setQryAlg(String qryAlg) {
		this.qryAlg = qryAlg;
	}
}