/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.scut24lab.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-30-2008
 * 
 * XDoclet definition:
 * @struts.form name="saveDSForm"
 */
public class SaveDSForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** connDriver property */
	private String connDriver;

	/** userName property */
	private String userName;

	/** connString property */
	private String connString;

	/** passWord property */
	private String passWord;

	/** url property */
	private String url;
	
	private String selSchName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the connDriver.
	 * @return String
	 */
	public String getConnDriver() {
		return connDriver;
	}

	/** 
	 * Set the connDriver.
	 * @param connDriver The connDriver to set
	 */
	public void setConnDriver(String connDriver) {
		this.connDriver = connDriver;
	}

	/** 
	 * Returns the userName.
	 * @return String
	 */
	public String getUserName() {
		return userName;
	}

	/** 
	 * Set the userName.
	 * @param userName The userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/** 
	 * Returns the connString.
	 * @return String
	 */
	public String getConnString() {
		return connString;
	}

	/** 
	 * Set the connString.
	 * @param connString The connString to set
	 */
	public void setConnString(String connString) {
		this.connString = connString;
	}

	/** 
	 * Returns the passWord.
	 * @return String
	 */
	public String getPassWord() {
		return passWord;
	}

	/** 
	 * Set the passWord.
	 * @param passWord The passWord to set
	 */
	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	/** 
	 * Returns the url.
	 * @return String
	 */
	public String getUrl() {
		return url;
	}

	/** 
	 * Set the url.
	 * @param url The url to set
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	public String getSelSchName() {
		return selSchName;
	}

	public void setSelSchName(String selSchName) {
		this.selSchName = selSchName;
	}
}