/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.scut24lab.struts.action;

import java.io.FileNotFoundException;
import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.jdom.JDOMException;

import com.scut24lab.struts.form.AddSchemaForm;

import data.web.olapschema.Schema;
import data.web.olapschema.Util;

/** 
 * MyEclipse Struts
 * Creation date: 04-04-2008
 * 
 * XDoclet definition:
 * @struts.action path="/addSchema" name="addSchemaForm" scope="request" validate="true"
 * @struts.action-forward name="addSchemaSuccess" path="/preComputeSuccess.jsp"
 * @struts.action-forward name="addSchemaFailure" path="/error.jsp"
 */
public class AddSchemaAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		AddSchemaForm addSchemaForm = (AddSchemaForm) form;
		
		HttpSession session = request.getSession(true);
		
		Schema schema = new Schema();
		String sName=addSchemaForm.getSchemaName();
		schema.setSchemaName(sName);
		
		// 保存到xml文件
		String xfpath = Util.getWebRootPath()+"/"+"DWServer/metadata/"+sName+".xml";
		try {
			schema.outToFile(xfpath);
		} catch (FileNotFoundException e) {
			e.printStackTrace();
			session.setAttribute("message", "写入"+xfpath+"时找到该文件");
			return mapping.findForward("addSchemaFailure");
		} catch (IOException e) {
			e.printStackTrace();
			session.setAttribute("message", "写入"+xfpath+"时发生IO异常");
			return mapping.findForward("addSchemaFailure");
		}catch(Exception e){
			e.printStackTrace();
			session.setAttribute("message", "写入"+xfpath+"时发生未知异常");
			return mapping.findForward("addSchemaFailure");
		}
		
		try {
			Util.setSchemaFilePath(sName, "DWServer/metadata/"+sName+".xml");
		} catch (JDOMException e) {
			e.printStackTrace();
			session.setAttribute("message", "向SchemaConfig.xml写入文件路径时不能解析SchemaConfig.xml");
			return mapping.findForward("addSchemaFailure");
			
		} catch (IOException e) {
			e.printStackTrace();
			session.setAttribute("message", "向SchemaConfig.xml写入文件路径时发生IO异常");
			return mapping.findForward("addSchemaFailure");
		}catch(Exception e){
			e.printStackTrace();
			session.setAttribute("message", "向SchemaConfig.xml写入文件路径时发生未知异常");
			return mapping.findForward("addSchemaFailure");
		}
		
		return mapping.findForward("addSchemaSuccess");
	}
}