/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-20-2008
 * 
 * XDoclet definition:
 * @struts.form name="createOdbcForm"
 */
public class CreateOdbcForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** desripton property */
	private String desripton;

	/** data_source_name property */
	private String data_source_name;

	/** path property */
	private String path;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the desripton.
	 * @return String
	 */
	public String getDesripton() {
		return desripton;
	}

	/** 
	 * Set the desripton.
	 * @param desripton The desripton to set
	 */
	public void setDesripton(String desripton) {
		this.desripton = desripton;
	}

	/** 
	 * Returns the data_source_name.
	 * @return String
	 */
	public String getData_source_name() {
		return data_source_name;
	}

	/** 
	 * Set the data_source_name.
	 * @param data_source_name The data_source_name to set
	 */
	public void setData_source_name(String data_source_name) {
		this.data_source_name = data_source_name;
	}

	/** 
	 * Returns the path.
	 * @return String
	 */
	public String getPath() {
		return path;
	}

	/** 
	 * Set the path.
	 * @param path The path to set
	 */
	public void setPath(String path) {
		this.path = path;
	}
}